import 'package:flutter/foundation.dart';

class AppLanguage extends ChangeNotifier {
  String _lang = 'ar';
  String get lang => _lang;

  void setLang(String value) {
    if (value == _lang) return;
    _lang = value;
    notifyListeners();
  }

  String t(String key) {
    final map = _lang == 'ar' ? _ar : _en;
    return map[key] ?? key;
  }
}

const Map<String, String> _ar = {
  'home': 'الرئيسية',
  'categories': 'الأقسام',
  'orders': 'الطلبات',
  'profile': 'الملف',
  'cart': 'العربة',
  'searchHint': 'ابحث عن منتج...',
  'todaysDeals': 'عروض اليوم',
  'allProducts': 'جميع المنتجات',
  'noProducts': 'لا توجد منتجات',
  'addToCart': 'إضافة إلى العربة',
  'addToCartShort': 'أضف للعربة',
  'favorites': 'المفضلة',
  'addresses': 'عناويني',
  'settings': 'الإعدادات',
  'support': 'الدعم الفني',
  'supportBody': 'تواصل معنا عبر الدعم الفني',
  'language': 'لغة التطبيق',
  'currency': 'جنيه',
  'discount': 'خصم',
  'description': 'الوصف',
  'reviewSaved': 'تم حفظ التقييم',
  'reviewsCount': 'عدد التقييمات',
  'myAddresses': 'عناويني',
  'addYourAddress': 'أضف عنوانك هنا',
  'editProfile': 'تعديل الملف الشخصي',
  'arabic': 'عربي',
  'english': 'English',
  'mustLogin': 'سجل الدخول لعرض المحتوى',
  'mustLoginFav': 'سجل الدخول لعرض المفضلة',
  'ordersEmpty': 'لا توجد طلبات',
  'cartEmpty': 'العربة فارغة',
  'checkout': 'إتمام الطلب',
  'orderSummary': 'ملخص العربة',
  'total': 'الإجمالي',
  'totalCart': 'إجمالي العربة',
  'fullName': 'الاسم الكامل',
  'phone': 'رقم الهاتف',
  'addressLabel': 'العنوان',
  'notesLabel': 'ملاحظات',
  'enterName': 'يرجى إدخال الاسم',
  'enterPhone': 'يرجى إدخال رقم الهاتف',
  'enterAddress': 'يرجى إدخال العنوان',
  'addedToCart': 'تمت الإضافة إلى العربة',
  'pending': 'قيد الانتظار',
  'preparing': 'جاري التجهيز',
  'shipped': 'في الطريق',
  'delivered': 'تم التسليم',
  'cancelled': 'ملغي',
  'cancelOrder': 'إلغاء الطلب',
  'cancelQuestion': 'هل تريد إلغاء هذا الطلب؟',
  'yes': 'نعم',
  'no': 'لا',
  'address': 'العنوان',
  'notes': 'ملاحظات',
  'similarProducts': 'منتجات مشابهة',
  'reviews': 'تقييمات العملاء',
  'addYourReview': 'أضف تقييمك',
  'noReviews': 'لا توجد تقييمات بعد',
  'outOfStock': 'غير متوفر',
  'available': 'متوفر',
  'today': 'اليوم',
  'login': 'تسجيل الدخول',
  'logout': 'تسجيل خروج',
  'profileEdit': 'تعديل الملف الشخصي',
  'about': 'عن التطبيق',
  'orderPlaced': 'تم الطلب بنجاح',
  'willContact': 'سيتم التواصل معك قريباً',
  'ok': 'حسناً',
  'emptyFav': 'لا توجد عناصر في المفضلة',
  'searching': 'جاري البحث...',
};

const Map<String, String> _en = {
  'home': 'Home',
  'categories': 'Categories',
  'orders': 'Orders',
  'profile': 'Profile',
  'cart': 'Cart',
  'searchHint': 'Search products...',
  'todaysDeals': "Today's Deals",
  'allProducts': 'All Products',
  'noProducts': 'No products',
  'addToCart': 'Add to cart',
  'addToCartShort': 'Add to cart',
  'favorites': 'Favorites',
  'addresses': 'My Addresses',
  'settings': 'Settings',
  'support': 'Support',
  'supportBody': 'Contact our support team',
  'language': 'App Language',
  'currency': 'EGP',
  'discount': 'off',
  'description': 'Description',
  'reviewSaved': 'Review saved',
  'reviewsCount': 'Reviews',
  'myAddresses': 'My Addresses',
  'addYourAddress': 'Add your address here',
  'editProfile': 'Edit Profile',
  'arabic': 'Arabic',
  'english': 'English',
  'mustLogin': 'Please sign in',
  'mustLoginFav': 'Sign in to view favorites',
  'ordersEmpty': 'No orders yet',
  'cartEmpty': 'Cart is empty',
  'checkout': 'Checkout',
  'orderSummary': 'Cart summary',
  'total': 'Total',
  'totalCart': 'Cart total',
  'fullName': 'Full name',
  'phone': 'Phone number',
  'addressLabel': 'Address',
  'notesLabel': 'Notes',
  'enterName': 'Please enter your name',
  'enterPhone': 'Please enter your phone',
  'enterAddress': 'Please enter your address',
  'addedToCart': 'Added to cart',
  'pending': 'Pending',
  'preparing': 'Preparing',
  'shipped': 'Shipped',
  'delivered': 'Delivered',
  'cancelled': 'Cancelled',
  'cancelOrder': 'Cancel order',
  'cancelQuestion': 'Do you want to cancel this order?',
  'yes': 'Yes',
  'no': 'No',
  'address': 'Address',
  'notes': 'Notes',
  'similarProducts': 'Related products',
  'reviews': 'Customer reviews',
  'addYourReview': 'Add your review',
  'noReviews': 'No reviews yet',
  'outOfStock': 'Out of stock',
  'available': 'Available',
  'today': 'Today',
  'login': 'Login',
  'logout': 'Logout',
  'profileEdit': 'Edit profile',
  'about': 'About',
  'orderPlaced': 'Order placed',
  'willContact': 'We will contact you soon',
  'ok': 'OK',
  'emptyFav': 'No favorites yet',
  'searching': 'Searching...',
};
