// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDef11jKH6O87I4_0U_OKD25aRAR7mO9A4',
    appId: '1:481576270136:web:1d771b808944497a8469cd',
    messagingSenderId: '481576270136',
    projectId: 'market-8c0f1',
    authDomain: 'market-8c0f1.firebaseapp.com',
    storageBucket: 'market-8c0f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDef11jKH6O87I4_0U_OKD25aRAR7mO9A4',
    appId: '1:481576270136:android:1d771b808944497a8469cd',
    messagingSenderId: '481576270136',
    projectId: 'market-8c0f1',
    storageBucket: 'market-8c0f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDef11jKH6O87I4_0U_OKD25aRAR7mO9A4',
    appId: '1:481576270136:ios:1d771b808944497a8469cd',
    messagingSenderId: '481576270136',
    projectId: 'market-8c0f1',
    storageBucket: 'market-8c0f1.firebasestorage.app',
    iosBundleId: 'com.example.alamirSupermarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDef11jKH6O87I4_0U_OKD25aRAR7mO9A4',
    appId: '1:481576270136:macos:1d771b808944497a8469cd',
    messagingSenderId: '481576270136',
    projectId: 'market-8c0f1',
    storageBucket: 'market-8c0f1.firebasestorage.app',
    iosBundleId: 'com.example.alamirSupermarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDef11jKH6O87I4_0U_OKD25aRAR7mO9A4',
    appId: '1:481576270136:windows:1d771b808944497a8469cd',
    messagingSenderId: '481576270136',
    projectId: 'market-8c0f1',
    storageBucket: 'market-8c0f1.firebasestorage.app',
  );
}
